/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'callNow' : IDL.Func([IDL.Text], [], []),
  'getAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getOpeningHours' : IDL.Func([], [IDL.Text], ['query']),
  'getPhoneNumber' : IDL.Func([], [IDL.Text], ['query']),
  'initiateWhatsApp' : IDL.Func([IDL.Text], [], []),
  'openGoogleMaps' : IDL.Func([IDL.Text], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'callNow' : IDL.Func([IDL.Text], [], []),
    'getAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getOpeningHours' : IDL.Func([], [IDL.Text], ['query']),
    'getPhoneNumber' : IDL.Func([], [IDL.Text], ['query']),
    'initiateWhatsApp' : IDL.Func([IDL.Text], [], []),
    'openGoogleMaps' : IDL.Func([IDL.Text], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };